language: go

matrix:
  include:
    - os: linux
      python: 3.5
      language: python
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
    - os: osx
      language: generic

script:
  - make check-go
  - make build-c
  - make build-py
  - make build-js
  - make clean-js
  - make clean-c
  - make clean-py
  - git checkout -- js/package-lock.json && git status --ignored
  - test -z "$(git status --porcelain --ignored | grep -v '[.]DS_Store' | grep -v 'go/')"


